# Generated by Django 4.2.2 on 2023-06-16 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auths', '0006_remove_users_birth_date_remove_users_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rs_number', models.IntegerField(verbose_name='Расчетный счет нашей системы')),
                ('balance', models.IntegerField(default=0, verbose_name='Баланс кошелька')),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to='auths.profile', verbose_name='Владелец')),
            ],
            options={
                'verbose_name': 'Кошелек',
                'verbose_name_plural': 'Кошельки',
            },
        ),
    ]
