# Generated by Django 4.2.2 on 2023-09-17 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='cvc',
            field=models.CharField(default='dasa', max_length=150, verbose_name='CVC'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wallet',
            name='expiry_month',
            field=models.CharField(default='2023-19-09', max_length=150, verbose_name='Месяц истечения'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wallet',
            name='expiry_year',
            field=models.CharField(default='2023-01-21', max_length=150, verbose_name='Год истечения'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='wallet',
            name='rs_number',
            field=models.CharField(max_length=150, verbose_name='Расчетный счет нашей системы'),
        ),
    ]
