# Generated by Django 4.2.2 on 2023-06-13 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0002_alter_users_is_owner_alter_users_is_superuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='is_staff',
            field=models.BooleanField(default=True),
        ),
    ]
