# Generated by Django 4.2.2 on 2023-06-13 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0003_alter_users_is_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='is_admin',
            field=models.BooleanField(default=True),
        ),
    ]
