# Generated by Django 4.2.2 on 2023-06-14 18:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0004_alter_users_is_admin'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='users',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.RemoveField(
            model_name='users',
            name='username',
        ),
        migrations.AddField(
            model_name='users',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='users',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, help_text='Никнейм пользователя', max_length=60, null=True, unique=True, verbose_name='Никнэйм')),
                ('user_image', models.ImageField(blank=True, help_text='Аватар', null=True, upload_to='', verbose_name='Аватарка на профиль')),
                ('bio', models.TextField(blank=True, null=True, verbose_name='Биография владельца')),
                ('instagram_link', models.TextField(blank=True, null=True, verbose_name='Ссылка на профиль в инстграмме')),
                ('user_profile', models.OneToOneField(help_text='Профиль', on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Чей профиль')),
            ],
        ),
    ]
