# Generated by Django 4.2.2 on 2023-09-17 12:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auths", "0008_emailverification"),
    ]

    operations = [
        migrations.AlterField(
            model_name="users",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
    ]
