# Generated by Django 4.2.2 on 2023-06-16 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('posts', '0002_alter_post_options'),
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('CREATED', 'STATUS_CREATED'), ('PROCESS', 'STATUS_PROCESS'), ('SUCCESS', 'STATUS_SUCCESS'), ('ROLLBACK', 'STATUS_ROLLBACK')], max_length=25, verbose_name='Статус платежа')),
                ('sum_of_post', models.IntegerField(verbose_name='Вводимая сумма')),
                ('is_transaction_finished', models.BooleanField(default=False, verbose_name='Транзакция закончена ли')),
                ('post_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='posts.post', verbose_name='Пост')),
                ('wallet_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallets', to='wallet.wallet', verbose_name='Кошелек')),
            ],
        ),
    ]
