# Generated by Django 4.2.2 on 2023-06-18 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('CREATED', 'STATUS_CREATED'), ('PROCESS', 'STATUS_PROCESS'), ('SUCCESS', 'STATUS_SUCCESS'), ('ROLLBACK', 'STATUS_ROLLBACK')], max_length=25, verbose_name='Статус платежа')),
                ('sum_of_post', models.IntegerField(verbose_name='Вводимая сумма')),
                ('is_transaction_finished', models.BooleanField(default=False, verbose_name='Транзакция закончена ли')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменено')),
            ],
            options={
                'verbose_name': 'Платеж',
                'verbose_name_plural': 'Платежи',
            },
        ),
    ]
